# Generated by Django 3.1.4 on 2021-01-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20210111_0241'),
        ('accounts', '0003_auto_20210111_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_city',
            field=models.ManyToManyField(blank=True, default=None, to='photo.City'),
        ),
    ]
