# Generated by Django 3.1.4 on 2021-01-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20210111_0242'),
        ('accounts', '0004_auto_20210111_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_city',
            field=models.ManyToManyField(blank=True, default=None, to='photo.City'),
        ),
    ]
