# Generated by Django 3.1.4 on 2021-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20210119_1237'),
        ('accounts', '0006_auto_20210115_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_city',
            field=models.ManyToManyField(blank=True, default=None, to='photo.City'),
        ),
    ]
