# Generated by Django 3.1.6 on 2021-02-13 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Локации-города',
                'verbose_name_plural': 'Локации-города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, default=None, max_length=50)),
                ('telephone', models.CharField(blank=True, default=None, max_length=15)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('gorod', models.CharField(blank=True, default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MoneyCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_today', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('dollar', models.FloatField(max_length=5, verbose_name='Доллар')),
                ('euro', models.FloatField(max_length=5, verbose_name='Евро')),
                ('rubl', models.FloatField(max_length=5, verbose_name='Рубль')),
                ('grivna', models.FloatField(max_length=5, verbose_name='Гривна')),
                ('funts', models.FloatField(max_length=5, verbose_name='Фунты')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
        migrations.CreateModel(
            name='PhotoSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('user', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('boat', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(default='Новая', max_length=30)),
                ('created_at', models.DateField(auto_now=True)),
                ('Client', models.ManyToManyField(blank=True, to='photo.Client')),
            ],
            options={
                'verbose_name': 'Фотосессия',
                'verbose_name_plural': 'Фотосессии',
            },
        ),
        migrations.CreateModel(
            name='PhotoToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('icon_type', models.CharField(blank=True, max_length=30, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Список товаров',
            },
        ),
        migrations.CreateModel(
            name='salsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, upload_to='photos/')),
                ('Photosessions', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photo.photosessions')),
            ],
            options={
                'verbose_name': 'Продажи',
                'verbose_name_plural': 'Продажиe',
            },
        ),
        migrations.CreateModel(
            name='PhotoTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Серийный номер')),
                ('extension_number', models.CharField(max_length=30, verbose_name='Внутрений номер')),
                ('DateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('DateEdit', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('Photo_tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.phototooltype', verbose_name='Тип техники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кому выдан')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='PhotoSessionsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, upload_to='photos/')),
                ('Photosessions', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photo.photosessions')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('city', models.ManyToManyField(blank=True, to='photo.City')),
            ],
            options={
                'verbose_name': 'Яхта',
                'verbose_name_plural': 'Список яхт',
            },
        ),
    ]
