# Generated by Django 3.1.4 on 2021-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoToolState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Состояние оборудования',
                'verbose_name_plural': 'Состояние оборудования',
            },
        ),
        migrations.AlterModelOptions(
            name='boat',
            options={'verbose_name': 'Яхта', 'verbose_name_plural': 'Список яхт'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Локации-города', 'verbose_name_plural': 'Локации-города'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='money_currency',
            options={'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курс валют'},
        ),
        migrations.AlterModelOptions(
            name='photosessions',
            options={'verbose_name': 'Фотосессия', 'verbose_name_plural': 'Фотосессии'},
        ),
        migrations.AlterModelOptions(
            name='phototool',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='phototooltype',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Тип оборудования'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Список товаров'},
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='date_today',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='dollar',
            field=models.FloatField(max_length=5, verbose_name='Доллар'),
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='euro',
            field=models.FloatField(max_length=5, verbose_name='Евро'),
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='funts',
            field=models.FloatField(max_length=5, verbose_name='Фунты'),
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='grivna',
            field=models.FloatField(max_length=5, verbose_name='Гривна'),
        ),
        migrations.AlterField(
            model_name='money_currency',
            name='rubl',
            field=models.FloatField(max_length=5, verbose_name='Рубль'),
        ),
        migrations.AlterField(
            model_name='phototooltype',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
    ]
