# Generated by Django 3.1.4 on 2021-01-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20210110_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototool',
            name='state',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='photo.phototoolstate'),
        ),
    ]
