# Generated by Django 3.1.4 on 2021-01-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_phototool_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototool',
            name='state',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='photo.phototoolstate', verbose_name='Состояние'),
        ),
    ]
