# Generated by Django 3.1.4 on 2021-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20210111_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosessionsimage',
            name='images',
            field=models.FileField(default=None, upload_to='media/photos'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='city',
            field=models.ManyToManyField(blank=True, to='photo.City'),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='Client',
            field=models.ManyToManyField(blank=True, to='photo.Client'),
        ),
    ]
