# Generated by Django 3.1.4 on 2021-01-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20210111_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='city',
            field=models.ManyToManyField(blank=True, to='photo.City'),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='Client',
            field=models.ManyToManyField(blank=True, to='photo.Client'),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='boat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
