# Generated by Django 3.1.4 on 2021-01-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20210111_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='city',
            field=models.ManyToManyField(blank=True, to='photo.City'),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='Client',
            field=models.ManyToManyField(blank=True, to='photo.Client'),
        ),
        migrations.AlterField(
            model_name='photosessionsimage',
            name='images',
            field=models.FileField(default=None, upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='salsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, upload_to='photos/')),
                ('Photosessions', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photo.photosessions')),
            ],
        ),
    ]
