# Generated by Django 3.1.4 on 2021-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20210115_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salsi',
            options={'verbose_name': 'Продажи', 'verbose_name_plural': 'Продажиe'},
        ),
        migrations.AlterField(
            model_name='boat',
            name='city',
            field=models.ManyToManyField(blank=True, to='photo.City'),
        ),
        migrations.AlterField(
            model_name='photosessions',
            name='Client',
            field=models.ManyToManyField(blank=True, to='photo.Client'),
        ),
    ]
